# Generated by Django 4.2.3 on 2023-07-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_image_profile_photo_remove_user_nickname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
    ]
